### ISSUE TITLE
[vite:build-html] Cannot be closed: body

### ISSUE THREAD

**Issue by jeff-fillmore** [lxs24sxl/vite-plugin-html-env#26]
Not sure what changed in 1.2.7 but now when building I'm getting error:

```
Error: Cannot be closed: body
    at ParseHTML.onCloseTagEndEvent (/Users/i868610/emarsys/campaign-blocks-client/node_modules/vite-plugin-html-env/lib/parse/index.js:313:15)
    at ParseHTML.parse (/Users/i868610/emarsys/campaign-blocks-client/node_modules/vite-plugin-html-env/lib/parse/index.js:189:16)
    at transform (/Users/i868610/emarsys/campaign-blocks-client/node_modules/vite-plugin-html-env/lib/index.js:141:19)
    at applyHtmlTransforms (file:///Users/i868610/emarsys/campaign-blocks-client/node_modules/vite/dist/node/chunks/dep-c842e491.js:44265:27)
    at Object.generateBundle (file:///Users/i868610/emarsys/campaign-blocks-client/node_modules/vite/dist/node/chunks/dep-c842e491.js:44185:32)
    at file:///Users/i868610/emarsys/campaign-blocks-client/node_modules/rollup/dist/es/shared/rollup.js:22748:40
```

If I remove the closing body tag than I get an error for the closing html tag:
```
Error: Cannot be closed: html
    at ParseHTML.onCloseTagEndEvent (/Users/i868610/emarsys/campaign-blocks-client/node_modules/vite-plugin-html-env/lib/parse/index.js:313:15)
    at ParseHTML.parse (/Users/i868610/emarsys/campaign-blocks-client/node_modules/vite-plugin-html-env/lib/parse/index.js:189:16)
    at transform (/Users/i868610/emarsys/campaign-blocks-client/node_modules/vite-plugin-html-env/lib/index.js:141:19)
    at applyHtmlTransforms (file:///Users/i868610/emarsys/campaign-blocks-client/node_modules/vite/dist/node/chunks/dep-c842e491.js:44265:27)
    at Object.generateBundle (file:///Users/i868610/emarsys/campaign-blocks-client/node_modules/vite/dist/node/chunks/dep-c842e491.js:44185:32)
    at file:///Users/i868610/emarsys/campaign-blocks-client/node_modules/rollup/dist/es/shared/rollup.js:22748:40
```

Not sure if this is meant to be but version 1.2.6 doesn't cause this error. 

Thanks,

**Comment by mattgreenfield** [comment]
I have the same error but it's a div. `Internal server error: Cannot be closed: div`. By the process of elimination, it seems to be caused by an HTML comment inside a div.
```html
<div>
      <!-- Remove this comment and the error goes away -->
</div>
```
If I move the comment up to be a direct child of the body I get `Cannot be closed: body` like you do.

I wonder if the issue is something todo with detecting `<` characters?

**Comment by jeff-fillmore** [comment]
@mattgreenfield thank you.  i move the comment to the head tag and it works.

**Comment by GabbyPly** [comment]
@mattgreenfield Nice!
Maybe we can get the package owner to add it to the npm docs?
